-- (b) Insert Data into ADVENTURE_TRIP Table
INSERT INTO ADVENTURE_TRIP (TRIP_ID, TRIP_NAME, START_LOCATION, STATE, DISTANCE, MAX_GRP_SIZE, TYPE, SEASON)
VALUES (45, 'Jay Peak', 'Jay', 'VT', 8, 8, 'Hiking', 'Summer');

-- Display the contents of ADVENTURE_TRIP Table
SELECT * FROM ADVENTURE_TRIP;